//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> PayerID { get; set; }
        public int Debt { get; set; }
        public bool IsOpen { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Payer Payer { get; set; }
    }
}
