//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loginDb
{
    using System;
    
    public enum Status : int
    {
        planned = 0,
        unpaid = 1,
        clientPaid = 2,
        payerPaid = 3,
        paid = 4
    }
}
